### ISSUE TITLE
change timestamp to TIMESTAMP datatype

### ISSUE THREAD

**Issue by chadwallacehart** [ObserveRTC/connector#1]
Request to change all instances of `timestamp` from Integer to timestamp datatype.

Currently timestamps show up as `INTEGER` in BigQuery. 100% of my queries involve filtering by date, so this means I need to do a `TIMESTAMP_MILLIS(timestamp)` before I touch anydate. I don't see any advantage to keeping this as an int. Some visualization tools expect a TIMESTAMP datatype or require extra work to manually treat the INTEGER field as a TIMESTAMP.

**Comment by balazskreith** [comment]
Thanks for the suggestion :) 
I added this change as part of the PR linked above. From now on all generated tables for bigquery, where it has the `timestamp` field in the BQ it will have the TIMESTAMP type.
